backend:
  # name: test-repo
  name: git-gateway
  branch: main

media_folder: "oiloftropynap/static/uploads"
public_folder: "/uploads"

collections:
  - name: "navbar"
    label: "Navbar"
    files:
      - file: "oiloftropynap/data/navbar.yml"
        label: "Navbar"
        name: "navbar"
        fields:
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "oiloftropynap/content/_index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "oiloftropynap/content/about.html"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Draft", name: "draft", widget: "boolean" }
          - { label: "Custom CSS", name: "custom_css", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "oiloftropynap/content/contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Draft", name: "draft", widget: "boolean" }
          - { label: "Custom CSS", name: "custom_css", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "oiloftropynap/content/illustrations.html"
        label: "Illustrations"
        name: "illustrations"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Draft", name: "draft", widget: "boolean" }
          - { label: "Custom CSS", name: "custom_css", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "oiloftropynap/content/overview.md"
        label: "Overview"
        name: "overview"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Draft", name: "draft", widget: "boolean" }
          - { label: "Custom CSS", name: "custom_css", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }